name: Extract Next.js Quran PDF

on: [workflow_dispatch]

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Playwright Script
        run: python extract.py

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Quran-Extracted-PDF
          path: Surah_1.pdf
